name: "xenminer docker image ci go"
on:
  push:
    paths:
      - Dockerfile-go
      - golang
  workflow_dispatch:

jobs:
  image-go:
    runs-on: ubuntu-latest
    steps:
      - name: "login ghcr.io"
        uses: docker/login-action@v2.0.0
        with:
          registry: "ghcr.io"
          username: ${{ github.repository_owner }}
          password: ${{ secrets.TOKEN }}
      - name: "login hub.docker.io"
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "setup qemu"
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          file: Dockerfile-go
          push: true
          tags: |
            docker.io/cnsumi/xen-miner-go:latest
            ghcr.io/cnsumi/xen-miner-go:latest
          platforms: |
            linux/amd64
            linux/arm64
