name: "xenminer docker image ci"
on:
  push:
    paths:
      - dockerfile
      - miner.py
      - requirements.txt
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "login hub.docker.io"
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: "setup qemu"
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: |
            docker.io/cnsumi/xen-miner:latest
          platforms: |
            linux/amd64
            linux/arm64
